# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 627)
        MainWindow.setStyleSheet("background:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 130))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Laplace_Equation.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.radiusInput = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radiusInput.setFont(font)
        self.radiusInput.setMinimum(1)
        self.radiusInput.setMaximum(9999)
        self.radiusInput.setProperty("value", 10)
        self.radiusInput.setObjectName("radiusInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radiusInput)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.bdryFunctionInput = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bdryFunctionInput.setFont(font)
        self.bdryFunctionInput.setObjectName("bdryFunctionInput")
        self.bdryFunctionInput.addItem("")
        self.bdryFunctionInput.addItem("")
        self.bdryFunctionInput.addItem("")
        self.bdryFunctionInput.addItem("")
        self.bdryFunctionInput.addItem("")
        self.bdryFunctionInput.addItem("")
        self.bdryFunctionInput.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bdryFunctionInput)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.aInput = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.aInput.setFont(font)
        self.aInput.setMinimum(-9999)
        self.aInput.setMaximum(9999)
        self.aInput.setProperty("value", 1)
        self.aInput.setObjectName("aInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.aInput)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.bInput = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bInput.setFont(font)
        self.bInput.setMinimum(-9999)
        self.bInput.setMaximum(9999)
        self.bInput.setProperty("value", -3)
        self.bInput.setObjectName("bInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bInput)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.functionOutputLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.functionOutputLabel.setFont(font)
        self.functionOutputLabel.setObjectName("functionOutputLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.functionOutputLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.CalculateButton = QtWidgets.QPushButton(self.widget)
        self.CalculateButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CalculateButton.setFont(font)
        self.CalculateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CalculateButton.setStyleSheet("")
        self.CalculateButton.setFlat(False)
        self.CalculateButton.setObjectName("CalculateButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.CalculateButton)
        self.verticalLayout.addWidget(self.widget)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_2.setObjectName("widget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.plottingYInput = QtWidgets.QSpinBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plottingYInput.setFont(font)
        self.plottingYInput.setMinimum(-9999)
        self.plottingYInput.setMaximum(9999)
        self.plottingYInput.setObjectName("plottingYInput")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.plottingYInput)
        self.plottingOptionInput = QtWidgets.QComboBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plottingOptionInput.setFont(font)
        self.plottingOptionInput.setObjectName("plottingOptionInput")
        self.plottingOptionInput.addItem("")
        self.plottingOptionInput.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plottingOptionInput)
        self.plottingXInput = QtWidgets.QSpinBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plottingXInput.setFont(font)
        self.plottingXInput.setMinimum(-9999)
        self.plottingXInput.setMaximum(9999)
        self.plottingXInput.setObjectName("plottingXInput")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.plottingXInput)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.plotButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plotButton.setFont(font)
        self.plotButton.setObjectName("plotButton")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.plotButton)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.CalculateButton.clicked.connect(MainWindow.calculateValue)
        self.plotButton.clicked.connect(MainWindow.plot)
        self.pushButton.clicked.connect(MainWindow.plot3D)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "r = "))
        self.label_3.setText(_translate("MainWindow", "f(x,y) = "))
        self.bdryFunctionInput.setItemText(0, _translate("MainWindow", "x^2+y^2"))
        self.bdryFunctionInput.setItemText(1, _translate("MainWindow", "12"))
        self.bdryFunctionInput.setItemText(2, _translate("MainWindow", "x^2-y^2"))
        self.bdryFunctionInput.setItemText(3, _translate("MainWindow", "x*sin(2*y)"))
        self.bdryFunctionInput.setItemText(4, _translate("MainWindow", "x^3-4*y"))
        self.bdryFunctionInput.setItemText(5, _translate("MainWindow", "cos(x*y)"))
        self.bdryFunctionInput.setItemText(6, _translate("MainWindow", "y"))
        self.label_4.setText(_translate("MainWindow", "a ="))
        self.label_5.setText(_translate("MainWindow", "b ="))
        self.label_6.setText(_translate("MainWindow", "u(a,b) ="))
        self.functionOutputLabel.setText(_translate("MainWindow", "empty"))
        self.CalculateButton.setText(_translate("MainWindow", "Calculate"))
        self.label_7.setText(_translate("MainWindow", "Plot the Graph"))
        self.label_8.setText(_translate("MainWindow", "Plot of fixed:"))
        self.label_10.setText(_translate("MainWindow", "y = "))
        self.plottingOptionInput.setItemText(0, _translate("MainWindow", "x"))
        self.plottingOptionInput.setItemText(1, _translate("MainWindow", "y"))
        self.label_9.setText(_translate("MainWindow", "x = "))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.pushButton.setText(_translate("MainWindow", "Plot 3D"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

